name: tasky
description: "Multi task application."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  flutter_native_splash: ^2.4.0
  flutter_screenutil: ^5.9.1
  intl_phone_field: ^3.2.0
  dotted_border: ^2.1.0
  pretty_qr_code: ^3.3.0
  readmore: ^3.0.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  shared_preferences: ^2.2.3
  get_it: ^7.7.0
  dio: ^5.4.3+1
  connectivity_plus: ^6.0.3
  flutter_bloc: ^8.1.5
  bloc: ^8.1.4
  phone_input: ^1.0.0
  toastification: ^2.0.0
  image_picker: ^1.1.1
  path_to_regexp: ^0.4.0
  intl: ^0.19.0
  http_parser: ^4.0.2
  flutter_staggered_animations: ^1.1.1
  qr_code_scanner: ^1.0.1
  skeletonizer: ^1.1.2+1
  flutter_svg: ^2.0.10+1
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: "AppIcon"
  remove_alpha_ios: true
  image_path: "assets/icons/ic_launcher-web.png"

flutter_native_splash:
  android: true
  ios: true
  web: false

  color: "#5F33E1"
  image: assets/icons/logo.png

  android_12:
    image: assets/icons/android_logo.png
    color: "#5F33E1"
